/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-08 17:37:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("	td {\r\n");
      out.write("		border-bottom:2px solid navy;\r\n");
      out.write("		padding:4px;\r\n");
      out.write("		border-bottom-left-radius:10px;\r\n");
      out.write("		border-bottom-right-radius:10px;\r\n");
      out.write("		font-family:verdana;\r\n");
      out.write("		box-shadow:2px 2px 4px gray;\r\n");
      out.write("	}\r\n");
      out.write("	th{\r\n");
      out.write("		border-bottom:2px solid navy;\r\n");
      out.write("		padding:10px;\r\n");
      out.write("		border-bottom-left-radius:10px;\r\n");
      out.write("		border-bottom-right-radius:10px;\r\n");
      out.write("		font-family:verdana;\r\n");
      out.write("		font-size:20px;\r\n");
      out.write("		box-shadow:3px 4px 8px gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	caption{\r\n");
      out.write("		border-bottom:2px solid navy;\r\n");
      out.write("		border-bottom-left-radius:10px;\r\n");
      out.write("		border-bottom-right-radius:10px;\r\n");
      out.write("		font-family:chiller;\r\n");
      out.write("		font-size:40px;\r\n");
      out.write("		box-shadow:2px 2px 9px gray;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<table style=\"padding:15px;text-align:center;\">		\r\n");
      out.write("		<caption>EMP TABLE</caption>\r\n");
      out.write("		<tr style=\"border:1px solid navy; padding:20px;\">\r\n");
      out.write("			<th >Employee No</th>\r\n");
      out.write("			<th >Employee Name</th>\r\n");
      out.write("			<th >Job</th>\r\n");
      out.write("			<th >Manager</th>\r\n");
      out.write("			<th >Hiredate</th>\r\n");
      out.write("			<th >Salary</th>\r\n");
      out.write("			<th >Commision</th>\r\n");
      out.write("			<th >Department No</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		");

		String url = "jdbc:oracle:thin:@localhost:1521:XE", userName = "protonium", passWord = "tiger";
		Connection conn;
		Statement stmt;
		PreparedStatement ps;
		ResultSet rs;

		try {
			/* out.println("URL SUCCEDED"); */
			Class.forName("oracle.jdbc.driver.OracleDriver");
			/* out.println("DRIVER LOADED"); */
			conn = DriverManager.getConnection(url, userName, passWord);
			ps = conn.prepareStatement("SELECT EMPNO ,ENAME , JOB ,	MGR , HIREDATE , SAL , COMM , DEPTNO  FROM EMP");
			rs = ps.executeQuery();
			while (rs.next()) {
				int no = rs.getInt("EMPNO");
				String name = rs.getString("ENAME");
				String job = rs.getString("JOB");
				int mgr = rs.getInt("MGR");
				Date date = rs.getDate("HIREDATE");
				int sal = rs.getInt("SAL");
				int comm = rs.getInt("COMM");
				int deptno = rs.getInt("DEPTNO");
		
      out.write("\r\n");
      out.write("		<tr style=\"border-bottom: 5px SOLID BLACK; padding:0px;\">\r\n");
      out.write("			<td >");
      out.print( no);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( name);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( job);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( mgr);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( date);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( sal);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( comm);
      out.write("</td>\r\n");
      out.write("			<td >");
      out.print( deptno);
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	");

	}
	} catch (Exception e) {

	}
	
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
